### PR TITLE
✨ Can hide NaN and set decimal places

### PR DESCRIPTION
**Pull request by ollyhensby**
♻️ Update VegaExpr so instead sets to default_renderer

### CODE REVIEW

**Comment by ollyhensby** [comment]
image
Appears to be rounding integers to 2dp too...

Let me resolve this

**Comment by ollyhensby** [comment]
> image Appears to be rounding integers to 2dp too...
> 
> Let me resolve this

Resolved

**Comment by ollyhensby** [comment]
Issue with hiding NaN if `global_decimal_places` not defined. Fix this before merging

**Review by jgunstone — APPROVED** [review]
looks good - thanks - 
I guess you commented out `lab_black` due to the dependencies issue...
if yes we should probs migrate one of these (in a separate issue):
- https://github.com/n8henrie/jupyter-black
- https://github.com/ryantam626/jupyterlab_code_formatter

**Comment by ollyhensby** [comment]
> Issue with hiding NaN if `global_decimal_places` not defined. Fix this before merging

Planned to fix this before merging but I will put this into a new issue and resolve there: https://github.com/maxfordham/ipyautoui/issues/196

**Pull request merged**
